"""empty message

Revision ID: a5d70bf33a72
Revises: d269f0f50288
Create Date: 2025-06-03 18:15:52.555160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d70bf33a72'
down_revision: Union[str, None] = 'd269f0f50288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terrains', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('terrains', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terrains', 'updated_at')
    op.drop_column('terrains', 'created_at')
    # ### end Alembic commands ###
