"""empty message

Revision ID: d269f0f50288
Revises: 
Create Date: 2025-06-03 17:17:26.285029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd269f0f50288'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('terrains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chemical_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('terrain_id', sa.UUID(), nullable=False),
    sa.Column('aluminum', sa.Float(), nullable=False),
    sa.Column('ammonium', sa.Float(), nullable=False),
    sa.Column('iron', sa.Float(), nullable=False),
    sa.Column('manganese', sa.Float(), nullable=False),
    sa.Column('copper', sa.Float(), nullable=False),
    sa.Column('nitrite', sa.Float(), nullable=False),
    sa.Column('phenols', sa.Float(), nullable=False),
    sa.Column('formaldehyde', sa.Float(), nullable=False),
    sa.Column('phosphates', sa.Float(), nullable=False),
    sa.Column('fluorides', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['terrain_id'], ['terrains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('terrain_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chemical_parameters')
    op.drop_table('terrains')
    op.drop_table('users')
    # ### end Alembic commands ###
